language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "iojs-v1"
  - "iojs-v2"
  - "iojs-v3"
  - "4"
  - "5"
  - "6"
env:
  - BROWSER=1
  - BROWSER_LOCAL=1
  - BROWSER_POLYFILL=1
  - ANY_PROMISE=
  - ANY_PROMISE=es6-promise
  - ANY_PROMISE=promise
  - ANY_PROMISE=native-promise-only
  - ANY_PROMISE=bluebird
  - ANY_PROMISE=rsvp
  - ANY_PROMISE=when
  # - ANY_PROMISE=q
