language: node_js
sudo: false
node_js:
  - "0.12"
  - "4.0"
  - "5.0"
env:
  - ANY_PROMISE=
  - ANY_PROMISE=es6-promise
  - ANY_PROMISE=promise
  - ANY_PROMISE=native-promise-only
  - ANY_PROMISE=bluebird
  - ANY_PROMISE=rsvp
  - ANY_PROMISE=when
  # - ANY_PROMISE=q
